version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - all-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    hostname: frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - all-network

networks:
  all-network:
    name: "all-network"
    driver: bridge
